# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qimHZFfWUrFPK1wd7TSFkorqgQKvQAzN
"""

from google.colab import files
uploaded = files.upload()

!pip install pyyaml h5py

!pip install python-aqi

import io
import pandas as pd
import numpy as np

can_yeni = pd.read_excel(io.BytesIO(uploaded['can_yeni.xlsx']))

istasyon = can_yeni.copy()
istasyon = istasyon.fillna(istasyon.mean())

import warnings
warnings.filterwarnings('ignore')

import aqi 
uzunluk = len(istasyon)
hki = np.zeros(uzunluk)
for i in range(uzunluk):
    me_hki = aqi.to_aqi([
        (aqi.POLLUTANT_PM10, istasyon['PM10'][i])], algo=aqi.ALGO_MEP)
    hki[i] = me_hki

def hava_kalite(x):
    if x <= 50:
        return "İyi"
    elif x <= 100:
        return "Yeterli"
    elif x <= 200:
        return "Orta"
    elif x <= 300:
        return "Kötü"
    elif x <= 400:
        return "Çok Kötü"
    elif x > 400:
        return "Ciddi"

kalite = []
for i in range(120):
    kalite.append(hava_kalite(hki[i]))

hava_kalite_deger = pd.DataFrame(hki)
hava_kalite_deger.columns = ['HKİ']
hava_kalite_deger.head()

kalite_deger = pd.DataFrame(kalite)
kalite_deger.columns = ['HKİ']
kalite_deger.head()